# Generated by Django 3.0.8 on 2020-07-24 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'verbose_name_plural': 'Waitlist entries'},
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
